### ISSUE TITLE
Extra slashes added to color tags on save

### ISSUE THREAD

**Issue by VRD01** [nelak2/nwscript-sinfar-language-server#1]
It looks like extra forward slashes are getting added to NWN color tags on autosave in VS Code.  

What was this:   <c\u00c5\u00e9J>  became this:  <c\\\u00c5\\\u00e9J>

Example is line 176 of:
atsm_ai_damaged.nss

which after numerous autosaves now has 8 slashes.

**Comment by nelak2** [comment]
The issue with the color tags should be resolved with the current version you're using
