### ISSUE TITLE
Refactor your functions in specified files

### ISSUE THREAD

**Issue by Arthurmtro** [nelak2/nwscript-sinfar-language-server#5]
You should separate your logic in specified files, this will allow you to better read, update and understand your code.
Plus, you may want to test your code in order to avoid a lot of errors

for example a folder `lib` with a folder `commands` with all commands so in your main file it will be more readable to just call the associated functions and don't care about what it does

https://github.com/nelak2/nwscript-sinfar-language-server/blob/c5afa5430fef7296ccdbac865df96269efc1e7b9/client/src/extension.ts#L86-L95

**Comment by nelak2** [comment]
Yes. This makes a lot of sense.
